### ISSUE TITLE
CLRerNet for the CurvLane and TuSimple datasets

### ISSUE THREAD

**Issue by FriendChi** [zkyntu/UnLanedet#28]
Thanks your work !! Could you provide the implementation of CLRerNet for the CurvLane and TuSimple datasets, or do you have any related suggestions or code that I can refer to?

**Comment by zkyntu** [comment]
Hi, we don't provide the implementation of CLRerNet for Tusimple since the official repo only contains the CULane dataset. However,  the simple implementation of applying CLRerNet to Tusimple is replacing the CLRHead with CLRerHead in CLRNet. We have provided the implementation of CLRNet for Tusimple. Hope this can solve your questions.

**Comment by zkyntu** [comment]
Currently, we don't support the CurveLane dataset. Maybe it can be provided in the future.

**Comment by FriendChi** [comment]
Thanks for your answer.
